workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - cd ios && pod install --repo-update && cd ..  # Обновляем Pods
      - flutter build ios --release --no-codesign  # Сборка для реального устройства
      - mkdir -p build/ios/ipa
      - zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip