workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: 3.29.2
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphoneos/Runner.app
