workflows:
  ios-build:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.ipa
