workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - cd ios
      - pod init
      - sed -i '' 's/# platform :ios, '\"'9.0\"'/platform :ios, '\"'13.0\"'/g' Podfile
      - cd ..
      - flutter pub get
      - flutter build ios --simulator
      - mkdir -p build/ios/ipa
      - zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip