workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build for iOS simulator
        script: |
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
